### ISSUE TITLE
Is there any way to add a reconnection to the database when the connection is lost?

### ISSUE THREAD

**Issue by mzujev** [kawansoft/aceql-http#11]
Dear AceQL developers and maintainers!

I am successfully connecting to postgreesql/mysql/oracle using aceql. But when the connection(from aceql to the database instance) is lost or restarted(database) I get the following error:
```log
org.kawanfw.sql.servlet.sql.LoggerUtil log
WARNING: Statement Exception: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. - SQL order: select pg_sleep(5)
org.kawanfw.sql.servlet.sql.LoggerUtil log
WARNING: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
org.apache.tomcat.jdbc.pool.PooledConnection clearWarnings
WARNING: Unable to clear Warnings, connection will be closed.
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:766)
        at org.postgresql.jdbc.PgConnection.clearWarnings(PgConnection.java:682)
        at org.apache.tomcat.jdbc.pool.PooledConnection.clearWarnings(PooledConnection.java:837)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.returnConnection(ConnectionPool.java:937)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:100)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:69)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy2.close(Unknown Source)
        at org.kawanfw.sql.api.server.DefaultDatabaseConfigurator.close(DefaultDatabaseConfigurator.java:142)
        at org.kawanfw.sql.servlet.ServerLogout.logout(ServerLogout.java:76)
        at org.kawanfw.sql.servlet.ServerSqlDispatch.executeRequestInTryCatch(ServerSqlDispatch.java:168)
        at org.kawanfw.sql.servlet.ServerSqlManager.handleRequest(ServerSqlManager.java:477)
        at org.kawanfw.sql.servlet.ServerSqlManager.handleRequestWrapper(ServerSqlManager.java:244)
        at org.kawanfw.sql.servlet.ServerSqlManager.access$0(ServerSqlManager.java:241)
        at org.kawanfw.sql.servlet.ServerSqlManager$1.run(ServerSqlManager.java:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
And now the question is, how to make it so that if the connection is lost, aceql reconnects to the database, regardless of the driver.

Best regards,
mzujev

**Comment by ndepomereu** [comment]
Hi mzujev,
AceQL follows the same mechanisms as using JDBC Connection Pool from a standard Web application.
 If you close the `Connection`, or the Web server is restarted,  the app has to extract a new one from the pool.

Could you be more specific about your need?

**Comment by mzujev** [comment]
Hi Nicolas,

Maybe I didn't describe the problem correctly. I will describe issue step by step
- starting aceql-server (databases = test and test.driverClassName = org.postgresql.Driver)
- connecting to aceql-server (curl reguest)
- curl request for current session (select pg_sleep(5))
- curl disconnect request

And result is:
```log
{
    "status":"OK",
    "query_rows":[
        {
            "row_1":[
                {
                    "pg_sleep":""
                }
            ]
        }
    ],
    "row_count":1
}
```
All seems to work correctly ...


Then after that i restart postgresql database and repeat step:
- connecting to aceql-server (curl reguest)

And i get this error, described above and this is logical, but not correct. In cases when the connection to the base is lost or the base is rebooted will need to restart aceql-server.

**Comment by ndepomereu** [comment]
Hi mzujev,
It is normal that after a restart of PostgreSQL database the connections are lost. Because all the Connection Pool is destroyed, you have to restart AceQL on the server. Ann then on client side, old Connections are brokken...
This work the same with a Web app using a JDBC Connection Pool.

I think this recovery mechanism should be included on your app on client side.
If you have more arguments, or examples of software that includes this recovery mechanism, I will glad to read you.
Meanwhile, I will think about it and try to find documentation on this matter.

**Comment by mzujev** [comment]
> It is normal that after a restart of PostgreSQL database the connections are lost.

This is logical(JDBC Connection Pool, etc), but this behavior not normal. Ok, i can understand, if AceQL act as a stateless proxy, then this behavior make sense.
Sorry, but what's the point in the gateway service, if the service doesn't have a mechanism to restore the connection to the database, it breaks every app that works through it with the database.

>I think this recovery mechanism should be included on your app on client-side.

I can't even imagine how to do that using app with AceQL, requests to the database still go through the aceql-server.

>If you have more arguments, or examples of software that include this recovery mechanism, I will glad to read you.

- Openresty with shared connection pool(mysql/pgsql)
- Oracle REST-Enabled SQL Service(not exactly the same, but very useful)

The convenience of AceQL is, that it combines multiple drivers for database access in one place with a single API. But with this issue, there is no make sense using AceQL in prodaction.

**Comment by ndepomereu** [comment]
Hi mzujev,
Got it!
I  reproduced the problem, and effectively, the JDBC Pool should be accessible after a PostgreSQL server restart, and there should be no login failure.
I will implement asap the correct behavior you are looking for.

**Comment by ndepomereu** [comment]
Hi mzujev,
Here is the promised "patch":
Just update your `aceql-server.properties` conf file with these 2 properties, and replace `sampledb `with your database name:

```
# testOnBorrow & validationQuery will ensure that the JDBC Connection Pool 
# is still accessible after the restart of the SQL engine in use. 
sampledb.testOnBorrow=true
sampledb.validationQuery=SELECT 1
```
Regards,
Nicolas

**Comment by mzujev** [comment]
Hi Nicolas,

I just tested it and it seems to works. SUPER!!!!

Now, we have a single gateway to different database over http. 

Thank you for your work.
